### ISSUE TITLE
Mobile View for the header dropdown

### ISSUE THREAD

**Issue by absarasw** [aemsites/phoenix#21]
Create the dialog for header dropdown. Add the logic to create the dropdown [here](https://github.com/aemsites/phoenix/blob/6a6524f6a807e83196236814dda5ab06098ac0d1/blocks/header/header.js#L408)

![image](https://github.com/aemsites/phoenix/assets/51747444/8b0f5f10-4f21-4d9a-b871-186881b7b1c4)
![image](https://github.com/aemsites/phoenix/assets/51747444/083588fa-9402-498f-b7d0-241dd7bbb79e)

**Comment by TobySuch** [comment]
Done in #39
