### ISSUE TITLE
Aside Nav

### ISSUE THREAD

**Issue by varu-adobe** [aemsites/phoenix#4]
Desktop:
<img width="340" alt="image" src="https://github.com/aemsites/phoenix/assets/85017932/875787aa-a135-4888-a8f8-9ced0ef582cc">

Mobile

<img width="390" alt="image" src="https://github.com/aemsites/phoenix/assets/85017932/eefc0f45-d2a2-421c-9881-00b998181e38">

**Comment by dipratap** [comment]
Completed as part of asidenav as fragment.
